name: Deploy static site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Change this to 'dist' or 'build' if you have a build output folder

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
